person:
#  name: "杨凌波 \n 测试双引号和单引号"
#  单引号会将\n 作为字符串输出  双引号会将\n 作为换行输出
#  双引号不会转义，单引号回转义
  boss: true
  birthday: 2001/02/11
  age: 21
  pet:
    name: tomcat
    weight: 212
#  hobbies: [跑步,编程]
  hobbies:
    - 跑步
    - 编程
  animal: [毛线,贝露,布点]
  score: {英语:90,数学:100,语文:99}
  salary:
    - 1291
    - 243434
  allPets:
    sick:
      - {name: 毛线,weight: 90}
      - {name: 贝露,weight: 21}
    health:
      - {name: 布点,weight: 12}